name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk
          pip install --upgrade pip

      - name: Install Buildozer
        run: |
          pip install buildozer cython

      - name: Install Android SDK
        run: |
          sudo apt install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-*.zip -d android-sdk
          mkdir -p android-sdk/cmdline-tools/latest
          mv android-sdk/cmdline-tools/* android-sdk/cmdline-tools/latest/ || true

      - name: Accept licenses
        run: yes | buildozer android accept_sdk_license

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
